name: sync up to AWS codecommit

#on:
#  push:
#    tags-ignore:
#      - '*'
#    branches:
#      - '*' 

on:      
  workflow_dispatch:
    inputs:
      tags:
        description: "branches"
        required: true
        default: '*'
        
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Sync up to CodeCommit
        uses: youyo/sync-up-to-codecommit-action@v1.0.6 #tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: mvp_custinfo_backend
          aws_region: ap-northeast-2
